Add tsc task and fix most compile errors
piotrwitek/react-ts-jspm-starter-kit pull request #16
Opened 2016-09-15 12:20 UTC by jonaskello

Fixes #15

2016-09-15 12:42 UTC, piotrwitek commented on src/tsconfig.json
> +    "skipLibCheck": true,
lib check is mandatory

2016-09-16 07:22 UTC, jonaskello commented
Agreed on skipLibCheck. I set it to false. I also did some more changes in tsconfig and now all compile errors but one is fixed. Specifically I had to change noResolve to false and module to commonjs. I did this by trial and error so not sure why.

The remaining error is this:
```
src/containers/currency-converter-container/components/currency-valuation-header                            -calendar.tsx(2,22): error TS2307: Cannot find module 'react-input-calendar'.
```

I think it might be because there are no types installed for react-input-calendar?

2016-09-16 07:48 UTC, piotrwitek commented
noResolve makes sense, because it strip out /// references to definition which are used in @types :)
IMO module should be system, because it will validate all various import types not only require
types for react-input-calendar should not be used, because the file actually importing that is not used by main app module, should check and fix includes in tsconfig

2016-09-16 11:16 UTC, piotrwitek commented on src/tsconfig.json
> +    "module": "commonjs",
please remove

2016-09-16 11:17 UTC, piotrwitek commented on src/tsconfig.json
> +    "lib": ["es5", "es6", "es2016.array.include", "dom", "es2016.array.include", "es2015.promise", "es2017.object", "es2015.iterable"],
please remove doubled es2016.array.include

2016-09-16 11:19 UTC, piotrwitek requested changes
With few additional fixes I have resolved this issue, please do requested changes and I'll merge this cr

2016-09-16 11:40 UTC, jonaskello commented
I think the requested changes are in now :-)

2016-09-16 14:59 UTC, piotrwitek approved these changes

2016-09-16 15:18 UTC, merged

2016-09-16 15:19 UTC, piotrwitek commented
@jonaskello merged, please check updated readme